# Auto-generated by Matugen

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --color=bg:{{colors.surface_container.default.hex}} \
  --color=fg:{{colors.on_surface.default.hex}} \
  --color=hl:{{colors.primary.default.hex}} \
  --color=bg+:{{colors.secondary_container.default.hex}} \
  --color=fg+:{{colors.on_secondary_container.default.hex}} \
  --color=hl+:{{colors.primary.default.hex}} \
  --color=info:{{colors.outline.default.hex}} \
  --color=prompt:{{colors.tertiary.default.hex}} \
  --color=pointer:{{colors.primary.default.hex}} \
  --color=marker:{{colors.inverse_primary.default.hex}} \
  --color=spinner:{{colors.primary.default.hex}} \
  --color=header:{{colors.on_surface_variant.default.hex}}"
